Little Update (Again)
- Refactor sum codes (I know my code still sucks, but hey, I'm trying my best)

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -6,9 +6,12 @@
 
 umask 022
 
-# echo before loading util_functions
-ui_print() { echo "$1"; }
+# Function to print messages
+ui_print() {
+  echo "$1"
+}
 
+# Function to require a newer version of Magisk
 require_new_magisk() {
   ui_print "*******************************"
   ui_print " Please install Magisk v20.4+! "
@@ -23,14 +26,21 @@ require_new_magisk() {
 OUTFD=$2
 ZIPFILE=$3
 
+# Mount /data partition
 mount /data 2>/dev/null
 
-[ -f /data/adb/magisk/util_functions.sh ] || require_new_magisk
-. /data/adb/magisk/util_functions.sh
-[ $MAGISK_VER_CODE -lt 20400 ] && require_new_magisk
+# Check if util_functions.sh exists and load it
+if [ ! -f /data/adb/magisk/util_functions.sh ]; then
+  require_new_magisk
+else
+  . /data/adb/magisk/util_functions.sh
+  if [ $MAGISK_VER_CODE -lt 20400 ]; then
+    require_new_magisk
+  fi
+fi
 
+# If Magisk version is 20.4 or newer, use the built-in installation logic
 if [ $MAGISK_VER_CODE -ge 20400 ]; then
-  # New Magisk have complete installation logic within util_functions.sh
   install_module
   exit 0
 fi
@@ -42,17 +52,18 @@ fi
 TMPDIR=/dev/tmp
 PERSISTDIR=/sbin/.magisk/mirror/persist
 
+# Function to check if the script is legacy
 is_legacy_script() {
   unzip -l "$ZIPFILE" install.sh | grep -q install.sh
   return $?
 }
 
+# Function to print module name and author
 print_modname() {
   local authlen len namelen pounds
-  namelen=`echo -n $MODNAME | wc -c`
-  authlen=$((`echo -n $MODAUTH | wc -c` + 3))
-  [ $namelen -gt $authlen ] && len=$namelen || len=$authlen
-  len=$((len + 2))
+  namelen=$(echo -n "$MODNAME" | wc -c)
+  authlen=$(( $(echo -n "$MODAUTH" | wc -c) + 3 ))
+  len=$((namelen > authlen ? namelen : authlen + 2))
   pounds=$(printf "%${len}s" | tr ' ' '*')
   ui_print "$pounds"
   ui_print " $MODNAME "
@@ -63,17 +74,18 @@ print_modname() {
   ui_print "*******************"
 }
 
-# Override abort as old scripts have some issues
+# Override abort function
 abort() {
   ui_print "$1"
   $BOOTMODE || recovery_cleanup
-  [ -n $MODPATH ] && rm -rf $MODPATH
-  rm -rf $TMPDIR
+  [ -n "$MODPATH" ] && rm -rf "$MODPATH"
+  rm -rf "$TMPDIR"
   exit 1
 }
 
-rm -rf $TMPDIR 2>/dev/null
-mkdir -p $TMPDIR
+# Clean up temporary directory
+rm -rf "$TMPDIR" 2>/dev/null
+mkdir -p "$TMPDIR"
 
 # Preparation for flashable zips
 setup_flashable
@@ -91,98 +103,98 @@ $BOOTMODE && boot_actions || recovery_actions
 # Preparation
 ##############
 
-# Extract prop file
-unzip -o "$ZIPFILE" module.prop -d $TMPDIR >&2
-[ ! -f $TMPDIR/module.prop ] && abort "! Unable to extract zip file!"
+# Extract module.prop file
+unzip -o "$ZIPFILE" module.prop -d "$TMPDIR" >&2
+[ ! -f "$TMPDIR/module.prop" ] && abort "! Unable to extract zip file!"
 
+# Determine module directory name and root
 $BOOTMODE && MODDIRNAME=modules_update || MODDIRNAME=modules
 MODULEROOT=$NVBASE/$MODDIRNAME
-MODID=`grep_prop id $TMPDIR/module.prop`
-MODNAME=`grep_prop name $TMPDIR/module.prop`
-MODAUTH=`grep_prop author $TMPDIR/module.prop`
+MODID=$(grep_prop id "$TMPDIR/module.prop")
+MODNAME=$(grep_prop name "$TMPDIR/module.prop")
+MODAUTH=$(grep_prop author "$TMPDIR/module.prop")
 MODPATH=$MODULEROOT/$MODID
 
-# Create mod paths
-rm -rf $MODPATH 2>/dev/null
-mkdir -p $MODPATH
+# Create module path
+rm -rf "$MODPATH" 2>/dev/null
+mkdir -p "$MODPATH"
 
 ##########
 # Install
 ##########
 
 if is_legacy_script; then
-  unzip -oj "$ZIPFILE" module.prop install.sh uninstall.sh 'common/*' -d $TMPDIR >&2
+  unzip -oj "$ZIPFILE" module.prop install.sh uninstall.sh 'common/*' -d "$TMPDIR" >&2
 
   # Load install script
-  . $TMPDIR/install.sh
+  . "$TMPDIR/install.sh"
 
   # Callbacks
   print_modname
   on_install
 
   # Custom uninstaller
-  [ -f $TMPDIR/uninstall.sh ] && cp -af $TMPDIR/uninstall.sh $MODPATH/uninstall.sh
+  [ -f "$TMPDIR/uninstall.sh" ] && cp -af "$TMPDIR/uninstall.sh" "$MODPATH/uninstall.sh"
 
   # Skip mount
-  $SKIPMOUNT && touch $MODPATH/skip_mount
+  $SKIPMOUNT && touch "$MODPATH/skip_mount"
 
-  # prop file
-  $PROPFILE && cp -af $TMPDIR/system.prop $MODPATH/system.prop
+  # Prop file
+  $PROPFILE && cp -af "$TMPDIR/system.prop" "$MODPATH/system.prop"
 
   # Module info
-  cp -af $TMPDIR/module.prop $MODPATH/module.prop
+  cp -af "$TMPDIR/module.prop" "$MODPATH/module.prop"
 
-  # post-fs-data scripts
-  $POSTFSDATA && cp -af $TMPDIR/post-fs-data.sh $MODPATH/post-fs-data.sh
+  # Post-fs-data scripts
+  $POSTFSDATA && cp -af "$TMPDIR/post-fs-data.sh" "$MODPATH/post-fs-data.sh"
 
-  # service scripts
-  $LATESTARTSERVICE && cp -af $TMPDIR/service.sh $MODPATH/service.sh
+  # Service scripts
+  $LATESTARTSERVICE && cp -af "$TMPDIR/service.sh" "$MODPATH/service.sh"
 
   ui_print "- Setting permissions"
   set_permissions
 else
   print_modname
 
-  unzip -o "$ZIPFILE" customize.sh -d $MODPATH >&2
+  unzip -o "$ZIPFILE" customize.sh -d "$MODPATH" >&2
 
-  if ! grep -q '^SKIPUNZIP=1$' $MODPATH/customize.sh 2>/dev/null; then
+  if ! grep -q '^SKIPUNZIP=1$' "$MODPATH/customize.sh" 2>/dev/null; then
     ui_print "- Extracting module files"
-    unzip -o "$ZIPFILE" -x 'META-INF/*' -d $MODPATH >&2
+    unzip -o "$ZIPFILE" -x 'META-INF/*' -d "$MODPATH" >&2
 
     # Default permissions
-    set_perm_recursive $MODPATH 0 0 0755 0644
+    set_perm_recursive "$MODPATH" 0 0 0755 0644
   fi
 
   # Load customization script
-  [ -f $MODPATH/customize.sh ] && . $MODPATH/customize.sh
+  [ -f "$MODPATH/customize.sh" ] && . "$MODPATH/customize.sh"
 fi
 
 # Handle replace folders
 for TARGET in $REPLACE; do
   ui_print "- Replace target: $TARGET"
-  mktouch $MODPATH$TARGET/.replace
+  mktouch "$MODPATH$TARGET/.replace"
 done
 
 if $BOOTMODE; then
   # Update info for Magisk Manager
-  mktouch $NVBASE/modules/$MODID/update
-  cp -af $MODPATH/module.prop $NVBASE/modules/$MODID/module.prop
+  mktouch "$NVBASE/modules/$MODID/update"
+  cp -af "$MODPATH/module.prop" "$NVBASE/modules/$MODID/module.prop"
 fi
 
 # Copy over custom sepolicy rules
-if [ -f $MODPATH/sepolicy.rule -a -e $PERSISTDIR ]; then
+if [ -f "$MODPATH/sepolicy.rule" ] && [ -e "$PERSISTDIR" ]; then
   ui_print "- Installing custom sepolicy patch"
-  # Remove old recovery logs (which may be filling partition) to make room
-  rm -f $PERSISTDIR/cache/recovery/*
+  rm -f "$PERSISTDIR/cache/recovery/*"
   PERSISTMOD=$PERSISTDIR/magisk/$MODID
-  mkdir -p $PERSISTMOD
-  cp -af $MODPATH/sepolicy.rule $PERSISTMOD/sepolicy.rule || abort "! Insufficient partition size"
+  mkdir -p "$PERSISTMOD"
+  cp -af "$MODPATH/sepolicy.rule" "$PERSISTMOD/sepolicy.rule" || abort "! Insufficient partition size"
 fi
 
-# Remove stuffs that don't belong to modules
+# Remove unnecessary files
 rm -rf \
-$MODPATH/system/placeholder $MODPATH/customize.sh \
-$MODPATH/README.md $MODPATH/.git* 2>/dev/null
+  "$MODPATH/system/placeholder" "$MODPATH/customize.sh" \
+  "$MODPATH/README.md" "$MODPATH/.git*" 2>/dev/null
 
 #############
 # Finalizing
@@ -190,7 +202,7 @@ $MODPATH/README.md $MODPATH/.git* 2>/dev/null
 
 cd /
 $BOOTMODE || recovery_cleanup
-rm -rf $TMPDIR
+rm -rf "$TMPDIR"
 
 ui_print "- Done"
 exit 0
